-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 19:00:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pg_Sistema_II
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pg_Sistema_II
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pg_Sistema_II` DEFAULT CHARACTER SET utf8 ;
USE `Pg_Sistema_II` ;

-- -----------------------------------------------------
-- Table `Pg_Sistema_II`.`Descendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pg_Sistema_II`.`Descendente` (
  `Desc_id` INT NOT NULL,
  `Desc_Respon_nome` VARCHAR(45) NULL,
  `Desc_Respon_cpf` VARCHAR(45) NULL,
  `Desc_nome` VARCHAR(45) NULL,
  `Desc_idade` INT NULL,
  `Desc_sexo` VARCHAR(4) NULL,
  PRIMARY KEY (`Desc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pg_Sistema_II`.`Responsável`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pg_Sistema_II`.`Responsável` (
  `Respon_id` INT NOT NULL,
  `Respon_cpf` VARCHAR(45) NULL,
  `Respon_nome` VARCHAR(45) NULL,
  `Respon_fone` VARCHAR(45) NULL,
  `Respon_email` VARCHAR(70) NULL,
  `Respon_endereco` VARCHAR(45) NULL,
  `Respon_idade` INT NULL,
  `Descendente_Desc_id` INT NOT NULL,
  PRIMARY KEY (`Respon_id`),
  CONSTRAINT `fk_Responsável_Descendente`
    FOREIGN KEY (`Descendente_Desc_id`)
    REFERENCES `Pg_Sistema_II`.`Descendente` (`Desc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Responsável_Descendente_idx` ON `Pg_Sistema_II`.`Responsável` (`Descendente_Desc_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pg_Sistema_II`.`Estadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pg_Sistema_II`.`Estadia` (
  `Estadia_id` INT NOT NULL,
  `Estadia_responsavel` VARCHAR(45) NULL,
  `Estadia_descendente` VARCHAR(45) NULL,
  `Estadia_Valor` DOUBLE NULL,
  `Estadia_temp_util` INT NULL,
  `Estadia_valorTotal` DOUBLE NULL,
  `Responsável_Respon_id` INT NOT NULL,
  PRIMARY KEY (`Estadia_id`, `Responsável_Respon_id`),
  CONSTRAINT `fk_Estadia_Responsável1`
    FOREIGN KEY (`Responsável_Respon_id`)
    REFERENCES `Pg_Sistema_II`.`Responsável` (`Respon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estadia_Responsável1_idx` ON `Pg_Sistema_II`.`Estadia` (`Responsável_Respon_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
